// Хранение локальных данных
const config = {
    score: FULL_BASE_CONFIGURATION.TIME,
    lvl: FULL_BASE_CONFIGURATION.LEVEL,
    hp: FULL_BASE_CONFIGURATION.HP,
    click: FULL_BASE_CONFIGURATION.YOUR_COINS,
    time: FULL_BASE_CONFIGURATION.START_TIME,
}
